=== bryan-klumpp/demo/Xml/accounts2.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!-- XML Schema generated by QTAssistant/XSD Module (http://www.paschidev.com) -->
<!-- from https://stackoverflow.com/questions/15770948/primary-and-foreign-keys-in-xml-schema -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://organize-your-accounts.com"
xmlns="http://organize-your-accounts.com"
elementFormDefault="qualified">
    <xs:element name="accounts">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Account" maxOccurs="unbounded"/>   
                <xs:element ref="Password" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>          
        </xs:complexType>
        <xs:key name="PKPasswords">
            <xs:selector xpath="Password/PasswordID"/>
            <xs:field xpath="@patt"/>
        </xs:key>
        <xs:keyref name="FKAccountToPassword" refer="PKPasswords">
            <xs:selector xpath="Account/PasswordID"/>
            <xs:field xpath="@patt"/>
        </xs:keyref>
    </xs:element>
    <xs:element name="Account">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Title" type="xs:string"/>
                <xs:element name="FirstName" type="xs:string"/>
                <xs:element name="LastName" type="xs:string"/>
                <xs:element name="Dateborn" type="xs:date"/>
                <xs:element name="Gender" type="xs:string"/>
                <xs:element name="AccountID" type="xs:string"/>
                <xs:element name="PasswordID" type="xs:string" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Password">
        <xs:complexType>
            <xs:sequence>
                <xs:element name = "firstname" type = "xs:string"/>
              </xs:sequence>
            <xs:attribute name="patt" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== bryan-klumpp/demo/Xml/accounts2.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!-- Sample XML generated by QTAssistant (http://www.paschidev.com) -->
<oa:accounts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:oa="http://organize-your-accounts.com"
xsi:schemaLocation="http://organize-your-accounts.com accounts2.xsd"
>
     <oa:Account>
        <oa:Title>Title1</oa:Title>
        <oa:FirstName>FirstName1</oa:FirstName>
        <oa:LastName>LastName1</oa:LastName>
        <oa:Dateborn>1900-01-01</oa:Dateborn>
        <oa:Gender>Gender1</oa:Gender>
        <oa:AccountID>AccountID1</oa:AccountID>
        <oa:PasswordID>PasswordID2</oa:PasswordID>
    </oa:Account>
    <oa:Account>
        <oa:Title>Title1</oa:Title>
        <oa:FirstName>FirstName1</oa:FirstName>
        <oa:LastName>LastName1</oa:LastName>
        <oa:Dateborn>1900-01-01</oa:Dateborn>
        <oa:Gender>Gender1</oa:Gender>
        <oa:AccountID>AccountID2</oa:AccountID>
        <oa:PasswordID>PasswordID1</oa:PasswordID>
    </oa:Account>
    <oa:Password patt="pwd1">
        <oa:firstname></oa:firstname>
     </oa:Password>
</oa:accounts>
