=== bryan-klumpp/demo/Xml/accounts.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!-- XML Schema generated by QTAssistant/XSD Module (http://www.paschidev.com) -->
<!-- from https://stackoverflow.com/questions/15770948/primary-and-foreign-keys-in-xml-schema -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="accounts">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Account" maxOccurs="unbounded"/>   
                <xs:element ref="Password" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>          
        </xs:complexType>
        <xs:key name="PKAccounts"> <!--https://stackoverflow.com/questions/4491983/xml-schema-key-keyref-how-to-use-them-->
            <xs:selector xpath="Account/AccountID"/>
            <xs:field xpath="."/>
        </xs:key>
        <xs:key name="PKPasswords">
            <xs:selector xpath="Password/PasswordID"/>
            <xs:field xpath="."/>
        </xs:key>
        <xs:keyref name="FKAccountToPassword" refer="PKPasswords">
            <xs:selector xpath="Account/PasswordID"/>
            <xs:field xpath="."/>
        </xs:keyref>
    </xs:element>
    <xs:element name="Account">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Title" type="xs:string"/>
                <xs:element name="FirstName" type="xs:string"/>
                <xs:element name="LastName" type="xs:string"/>
                <xs:element name="Dateborn" type="xs:date"/>
                <xs:element name="Gender" type="xs:string"/>
                <xs:element name="AccountID" type="xs:string"/>
                <xs:element name="PasswordID" type="xs:string" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Password">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="PasswordID" type="xs:string"/>
                <xs:element name="Street" type="xs:string"/>
                <xs:element name="City" type="xs:string"/>
                <xs:element name="Province" type="xs:string" minOccurs="0"/>
                <xs:element name="Country" type="xs:date" minOccurs="0"/>
                <xs:element name="PostalCode" type="xs:string" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== bryan-klumpp/demo/Xml/accounts.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!-- Sample XML generated by QTAssistant (http://www.paschidev.com) -->
<accounts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="accounts.xsd">
     <Account>
        <Title>Title1</Title>
        <FirstName>FirstName1</FirstName>
        <LastName>LastName1</LastName>
        <Dateborn>1900-01-01</Dateborn>
        <Gender>Gender1</Gender>
        <AccountID>AccountID1</AccountID>
        <PasswordID>PasswordID2</PasswordID>
    </Account>
    <Account>
        <Title>Title1</Title>
        <FirstName>FirstName1</FirstName>
        <LastName>LastName1</LastName>
        <Dateborn>1900-01-01</Dateborn>
        <Gender>Gender1</Gender>
        <AccountID>AccountID2</AccountID>
        <PasswordID>PasswordID1</PasswordID>
    </Account>
    <Password>
        <PasswordID>PasswordID1</PasswordID>
        <Street>Street1</Street>
        <City>City1</City>
        <Province>Province1</Province>
        <Country>1900-01-01</Country>
        <PostalCode>PostalCode1</PostalCode>
    </Password>
    <Password>
        <PasswordID>PasswordID2</PasswordID>
        <Street>Street1</Street>
        <City>City1</City>
        <Province>Province1</Province>
        <Country>1900-01-01</Country>
        <PostalCode>PostalCode1</PostalCode>
    </Password>
</accounts>
